name: cargo_driver_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.1
  motion_tab_bar_v2: ^0.3.0
  intl: ^0.18.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  country_code_picker: ^3.0.0
  pinput: ^4.0.0
  image_picker: ^1.0.7
  google_maps_flutter: ^2.6.1
  loading_animation_widget: ^1.2.1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  flutter_polyline_points_plus: 
  dotted_line: ^3.2.2
#  mqtt_client: ^10.2.1
  typed_data: ^1.3.2
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^17.1.2
  image: ^3.0.1
  firebase_core: ^2.31.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # example:
  fonts:
    - family: RadioCanada
      fonts:
        - asset: fonts/RadioCanada-Regular.ttf
        - asset: fonts/RadioCanada-Light.ttf
        - asset: fonts/RadioCanada-Medium.ttf
        - asset: fonts/RadioCanada-SemiBold.ttf
        - asset: fonts/RadioCanada-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
