// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuk7j66HBlAp4ajs_MiTCQnrqAmK1tWq4',
    appId: '1:19132754693:web:d40896acb378b4f0d3a56c',
    messagingSenderId: '19132754693',
    projectId: 'tarud-driver-app',
    authDomain: 'tarud-driver-app.firebaseapp.com',
    storageBucket: 'tarud-driver-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxVciGgEmK7OsLwNQJjrjHd8JFhXrElA',
    appId: '1:705442055445:android:7856024472ed7bba53151c',
    messagingSenderId: '705442055445',
    projectId: 'cargo-driver-app-8bedd',
    storageBucket: 'cargo-driver-app-8bedd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQREp5_Ddt9tTvC7c4bTp2T2PEM6MBkt8',
    appId: '1:705442055445:ios:85a0a4dc35a7332753151c',
    messagingSenderId: '705442055445',
    projectId: 'cargo-driver-app-8bedd',
    storageBucket: 'cargo-driver-app-8bedd.appspot.com',
    iosBundleId: 'com.iOS.cargoDriverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL-CodF5zzy0VYEF5MyAh4Sn_l7T80fxc',
    appId: '1:19132754693:ios:1e471b7db320ba07d3a56c',
    messagingSenderId: '19132754693',
    projectId: 'tarud-driver-app',
    storageBucket: 'tarud-driver-app.appspot.com',
    iosBundleId: 'com.example.cargoDriverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuk7j66HBlAp4ajs_MiTCQnrqAmK1tWq4',
    appId: '1:19132754693:web:f5c03753e0cb4f02d3a56c',
    messagingSenderId: '19132754693',
    projectId: 'tarud-driver-app',
    authDomain: 'tarud-driver-app.firebaseapp.com',
    storageBucket: 'tarud-driver-app.appspot.com',
  );
}